
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "edev"
version = "0.2.0"
description = "Educational developer utilities (number theory)"
authors = [{name = "Ermuhammadov Elshod"}]
requires-python = ">=3.8"
